# Generated by Django 5.2.7 on 2025-10-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelmssa',
            old_name='mape',
            new_name='mae',
        ),
    ]
