# Generated by Django 5.2.7 on 2025-10-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_mape_modelmssa_mae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='indeks_kualitas_udara',
            field=models.CharField(max_length=40),
        ),
    ]
