# Generated by Django 5.2.7 on 2025-10-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_predictionresult_indeks_kualitas_udara'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmssa',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelmssa', to='API.station'),
        ),
    ]
