# Generated by Django 5.2.7 on 2025-11-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_modelmssa_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelmssa',
            name='persamaan_LRF',
        ),
        migrations.AddField(
            model_name='modelmssa',
            name='lag_data',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
